import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProtector from "@/components/login/AuthProtector";
import { AppContextProvider } from "@/context/AppContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
      >
        <div className="dark:bg-gradient-to-b dark:from-[#242124] dark:to-[#000]">
          <AppContextProvider>
            <AuthProtector>
              <Toaster />
              {children}
            </AuthProtector>
          </AppContextProvider>
        </div>
      </body>
    </html>
  );
}
